# Generated by Django 4.1.3 on 2022-12-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frequently_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('show_in_index', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی سایت')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
    ]
