# Generated by Django 4.1.3 on 2022-12-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Frequently_Question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequently_question',
            options={'ordering': ['-id'], 'verbose_name': 'سوال متداول', 'verbose_name_plural': 'سوالات متداول'},
        ),
    ]
