# Generated by Django 4.1.3 on 2022-11-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس های کاربر', 'verbose_name_plural': 'آدرس های کاربران'},
        ),
    ]
