# Generated by Django 4.1.3 on 2022-11-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_User', '0003_alter_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
