# Generated by Django 4.1.3 on 2022-11-21 11:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_Product', '0006_alter_product_slug'),
        ('app_User', '0004_remove_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='کل مبلغ')),
                ('submit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت سفارش')),
                ('delivery_status', models.BooleanField(default=False, verbose_name='وضعیت ارسال')),
                ('tracking_code', models.CharField(default='f6166563e4cc', max_length=12, unique=True, verbose_name='کد رهگیری')),
                ('delivery_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery', to='app_Product.delivery_mode', verbose_name='نوع ارسال')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='جمع قیمت(تومان)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_order', to='app_Orders.orders', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_product_material', to='app_Product.materialmodel', verbose_name='محصولات')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(related_name='order_product', through='app_Orders.ProductsModel', to='app_Product.materialmodel', verbose_name='محصولات'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_and_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_address_user', to='app_User.address', verbose_name='کاربر و آدرس گیرنده'),
        ),
    ]
