# Generated by Django 4.1.3 on 2022-11-21 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Product', '0006_alter_product_slug'),
        ('app_Orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsmodel',
            options={'verbose_name': 'محصول سفارش داده شده', 'verbose_name_plural': 'محصولات سفارش داده شده'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='کل مبلغ سفارش(تومان)'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tracking_code',
            field=models.CharField(default='3a7e2c4eea90', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_product_material', to='app_Product.materialmodel', verbose_name='محصول'),
        ),
    ]
