# Generated by Django 4.1.3 on 2022-12-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Orders', '0003_alter_orders_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='tracking_code',
            field=models.CharField(default='7885acfb3567', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
