# Generated by Django 4.1.3 on 2022-12-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Orders', '0011_alter_orders_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='discount_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ تخفیف خورده'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tracking_code',
            field=models.CharField(default='81fb7d0875db', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
