# Generated by Django 4.1.3 on 2022-12-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Orders', '0014_alter_orders_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='tracking_code',
            field=models.CharField(default='3e36965a90f2', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
