# Generated by Django 4.1.3 on 2022-12-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Orders', '0015_alter_orders_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='description',
            field=models.TextField(default='خالی', null=True, verbose_name='توضیحات کاربر قبل از انجام سفارش'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tracking_code',
            field=models.CharField(default='7f49db5d8266', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
