# Generated by Django 4.1.3 on 2022-12-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Orders', '0017_alter_orders_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='tracking_code',
            field=models.CharField(default='6ac5b8fea62d', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
