# Generated by Django 4.1.3 on 2022-12-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Orders', '0020_remove_orders_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('CNS', 'لغو شده'), ('SUC', 'تحویل داده شده'), ('AWC', 'در انتظار تایید'), ('PRE', 'در حال آماده سازی')], default='AWC', max_length=3, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tracking_code',
            field=models.CharField(default='e6ce2bd8aab0', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
