# Generated by Django 4.1.3 on 2023-01-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Orders', '0022_alter_orders_admin_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='tracking_code',
            field=models.CharField(default='8b238e73be19', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
