# Generated by Django 4.1.3 on 2023-01-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Orders', '0023_alter_orders_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='tracking_code',
            field=models.CharField(default='f20ad2abe504', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
