# Generated by Django 4.1.3 on 2023-01-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Orders', '0024_alter_orders_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='tracking_code',
            field=models.CharField(default='a9537bd6b75a', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
