# Generated by Django 4.1.3 on 2023-01-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Orders', '0026_alter_orders_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='tracking_code',
            field=models.CharField(default='70fca632b843', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
