# Generated by Django 4.1.3 on 2022-12-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, verbose_name='شماره تماس')),
                ('address', models.CharField(max_length=50, verbose_name='ادرس')),
                ('week_hours_work', models.CharField(max_length=10, verbose_name='ساعت کاری شنبه الی چهارشنبه')),
                ('weekend_hours_work', models.CharField(max_length=10, verbose_name='ساعت کاری پنجشنبه')),
            ],
            options={
                'verbose_name': 'ایتم تنظیم سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
