# Generated by Django 4.1.3 on 2022-12-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteoptions',
            name='address',
            field=models.TextField(max_length=50, verbose_name='ادرس'),
        ),
    ]
