# Generated by Django 4.1.3 on 2022-12-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Settings', '0002_alter_siteoptions_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteoptions',
            name='address',
            field=models.TextField(verbose_name='ادرس'),
        ),
    ]
