# Generated by Django 4.1.3 on 2022-12-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Settings', '0003_alter_siteoptions_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteoptions',
            name='low_off_product_inventory',
            field=models.BooleanField(default=True, verbose_name='کم کردن موجودی محصولات بعد از ثبت سفارش کاربران'),
        ),
    ]
