# Generated by Django 4.1.3 on 2022-11-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
        migrations.AlterField(
            model_name='delivery_mode',
            name='price',
            field=models.CharField(blank=True, default='متغیر', max_length=25, null=True, verbose_name='قیمت ارسال(تومان)'),
        ),
        migrations.AlterField(
            model_name='materialmodel',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت واحد(تومان)'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
