# Generated by Django 4.1.3 on 2022-11-20 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Material', '0001_initial'),
        ('app_Product', '0003_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialmodel',
            options={'verbose_name': 'سایز و جنس', 'verbose_name_plural': 'سایز ها و جنس ها'},
        ),
        migrations.AlterField(
            model_name='materialmodel',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_material', to='app_Material.material', verbose_name='نوع ماده'),
        ),
        migrations.AlterField(
            model_name='materialmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_product', to='app_Product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='materialmodel',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_size', to='app_Material.size', verbose_name='اندازه'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='app_Product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_modes',
            field=models.ManyToManyField(related_name='product_delivery_mode', to='app_Product.delivery_mode', verbose_name='انواع ارسال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounts',
            field=models.ManyToManyField(related_name='product_discounts', to='app_Product.discount', verbose_name='تخفیف ها'),
        ),
    ]
