# Generated by Django 4.1.3 on 2022-11-20 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_Product', '0004_alter_materialmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='tarash', max_length=100, unique=True, verbose_name='لینک انگلیسی'),
        ),
    ]
