# Generated by Django 4.1.3 on 2022-11-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Product', '0005_product_created_date_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='لینک انگلیسی'),
        ),
    ]
