# Generated by Django 4.1.3 on 2022-12-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Product', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_modes',
        ),
        migrations.AddField(
            model_name='product',
            name='productId',
            field=models.CharField(default='43574b6ec173', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
