# Generated by Django 4.1.3 on 2022-12-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Product', '0007_remove_product_delivery_modes_product_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_index',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی سایت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.CharField(default='e769089a1100', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
