# Generated by Django 4.1.3 on 2022-12-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Product', '0010_alter_discount_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.CharField(default='9dcb254bc6b5', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
