# Generated by Django 4.1.3 on 2022-12-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Product', '0014_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.CharField(default='ad8141bdda9c', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
