# Generated by Django 4.1.3 on 2022-12-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Product', '0015_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.CharField(default='a531670aeb7e', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
