# Generated by Django 4.1.3 on 2022-12-14 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Product', '0021_productpreparationtime_alter_product_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preparation_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_Product.productpreparationtime', verbose_name='زمان آماده سازی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.CharField(default='ea6b5021d5e9', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
