# Generated by Django 4.1.3 on 2022-12-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Product', '0022_product_preparation_time_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.CharField(default='904e6cd9ee19', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
