# Generated by Django 4.1.3 on 2022-12-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Product', '0023_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.CharField(default='5bfb6d920bfb', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
