# Generated by Django 4.1.3 on 2023-01-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Product', '0026_alter_product_productid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='نام')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='لینک')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.CharField(default='c6f4bf74dc6c', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='product_categories', to='app_Product.categories', verbose_name='دسته ها'),
        ),
    ]
