# Generated by Django 4.1.3 on 2023-01-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Product', '0027_categories_alter_product_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.CharField(default='42a02421c699', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
