# Generated by Django 4.1.3 on 2023-01-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Product', '0029_alter_product_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.CharField(default='6cce118d928a', max_length=12, unique=True, verbose_name='کد رهگیری'),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
