# Generated by Django 4.1.3 on 2022-11-19 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=25, verbose_name='رنگ')),
                ('ingredient', models.CharField(max_length=25, verbose_name='جنس')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'متریال',
                'verbose_name_plural': 'متریال ها',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='عرض')),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='طول')),
                ('height', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عرض')),
            ],
            options={
                'verbose_name': 'اندازه',
                'verbose_name_plural': 'اندازه ها',
            },
        ),
    ]
