# Generated by Django 4.1.3 on 2022-11-21 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='height',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عرض(سانتی متر)'),
        ),
        migrations.AlterField(
            model_name='size',
            name='length',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='طول(سانتی متر)'),
        ),
        migrations.AlterField(
            model_name='size',
            name='width',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='عرض(سانتی متر)'),
        ),
    ]
